# taks related to librenms as librenms user

# Can no longer clone into /opt/librenms as the directory is created earlier.
- name: Fetch and unzip librenms
  unarchive:
    src: "https://github.com/librenms/librenms/archive/{{ librenms_version }}.tar.gz"
    dest: /opt/
    remote_src: yes
    creates: /opt/librenms/html/index.php
  register: librenms_fetch_result

- name: "Move librenms to {{ librenms_dir }}"
  shell: "mv /opt/librenms-{{ librenms_version }}/* {{ librenms_dir }}/."
  when: librenms_fetch_result.changed

- name: "Remove /opt/linbrenms-{{ librenms_version }}"
  file:
    path: "/opt/librenms-{{ librenms_version }}"
    state: absent
  when: librenms_fetch_result.changed

- name: Create librenms configuration
  template:
    src: config.php.j2
    dest: "{{librenms_dir}}/config.php"

- name: Create rrd and logs directories
  file:
    group: "{{ librenms_group }}"
    owner: "{{ librenms_user }}"
    path: "{{librenms_dir}}/{{ item }}"
    state: directory
  with_items:
    - logs
    - rrd

- name: Initialise the librenms database
  shell: "php build-base.php"
  args:
    chdir: "{{librenms_dir}}"
  when: librenms_fetch_result.changed

- name: get list of users
  shell: "echo select username from users | mysql -ulibrenms -p{{ librenms_db_pass }} librenms"
  changed_when: False
  register: librenms_user_list

- name: Create librenms admin user
  shell: "php adduser.php {{ librenms_admin_user }} {{ librenms_admin_pass }} 10 {{ monitor_admin_email }}"
  args:
    chdir: "{{librenms_dir}}"
  when: "librenms_admin_user not in librenms_user_list.stdout_lines"

- name: Validate the librenms install
  shell: "php validate.php"
  args:
    chdir: "{{librenms_dir}}"
  when: librenms_fetch_result.changed

- name: get list of hosts
  shell: "echo select hostname from devices | mysql -ulibrenms -p{{ librenms_db_pass }} librenms"
  changed_when: False
  register: librenms_host_list

- name: Add localhost to monitored devices (Ignore errors about existing hosts)
  shell: "php addhost.php localhost {{ snmp_community }} v2c"
  args:
    chdir: "{{librenms_dir}}"
  when: "'localhost' not in librenms_host_list.stdout_lines"

- name: Discover hosts - disabled
  shell: "php discovery.php -h all"
  args:
    chdir: "{{librenms_dir}}"
  when: False
