# taks related to librenms as librenms user
- name: Clone librenms from github
  git:
    repo: https://github.com/librenms/librenms.git
    dest: "{{librenms_dir}}"
    depth: 1
    version: "{{ librenms_version }}"
  register: librenms_git_result

- debug: var=librenms_git_result

- name: Create librenms configuration
  template:
    src: config.php.j2
    dest: "{{librenms_dir}}/config.php"

- name: Create rrd and logs directories
  file:
    group: "{{ librenms_group }}"
    owner: "{{ librenms_user }}"
    path: "{{librenms_dir}}/{{ item }}"
    state: directory
  with_items:
    - logs
    - rrd

- name: Initialise the librenms database
  shell: "php build-base.php"
  args:
    chdir: "{{librenms_dir}}"
  when: librenms_git_result.changed

- name: Create librenms admin user
  shell: "php adduser.php {{ librenms_admin_user }} {{ librenms_admin_pass }} 10 {{ monitor_admin_email }}"
  args:
    chdir: "{{librenms_dir}}"

- name: Validate the librenms install
  shell: "php validate.php"
  args:
    chdir: "{{librenms_dir}}"

- name: Add localhost to monitored devices (Ignore errors about existing hosts)
  shell: "php addhost.php localhost {{ snmp_community }} v2c"
  args:
    chdir: "{{librenms_dir}}"
  ignore_errors: yes

- name: Discover localhost
  shell: "php discovery.php -h all"
  args:
    chdir: "{{librenms_dir}}"
